[package]
name = "libz-ng-sys"
version = "1.1.16"
authors = [
    "Alex Crichton <alex@alexcrichton.com>",
    "Josh Triplett <josh@joshtriplett.org>",
    "Sebastian Thiel <sebastian.thiel@icloud.com>",
]
links = "z-ng"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rust-lang/libz-sys"
description = "Low-level bindings to zlib-ng (libz-ng), a high-performance zlib library."
categories = ["compression", "external-ffi-bindings"]
keywords = ["zlib", "zlib-ng"]
edition = "2018"

exclude = [
    "/.github",
    "/.gitmodules",
    "/README.md",
    "/build.rs",
    "/cargo-zng",
    "/ci",
    "/src/smoke.c",
    "/src/zlib",
    "/systest",
]

build = "zng/cmake.rs"
readme = "README-zng.md"

[workspace]
members = ["systest"]

[dependencies]
libc = "0.2.43"

[build-dependencies]
cmake = "0.1.50"

[features]
# Experimental: This feature only affects zlib-ng, is only relevant to riscv64
# targets, and currently only has an effect when `cmake` is used. It builds
# binaries portable to machines without RVV, even if the build machine is
# riscv64 and detected to support RVV. This is useful for building a more
# portable binary, or on systems where auto-detection is incorrect
# (as in https://github.com/zlib-ng/zlib-ng/issues/1705).
rvv-off = []

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(zng)'] }
